language: c

os:
    - osx
    - linux

compiler:
    - clang
    - gcc

script:
    - make test

env:
    global:
        - MAKEFLAGS="-j"

branches:
    only:
        - master

notifications:
    email:
        on_success: always
        on_failure: always
